"""add model bookings

Revision ID: 1438e0266b40
Revises: 146691a88df6
Create Date: 2024-01-16 16:03:10.466513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438e0266b40'
down_revision = '146691a88df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
