"""add model bookings

Revision ID: ebcc55eae3e7
Revises: 1438e0266b40
Create Date: 2024-01-16 16:04:58.567104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcc55eae3e7'
down_revision = '1438e0266b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
